#Service API
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 5000
    #  nodePort: 30000
  type: LoadBalancer #NodPort era antes localmente

---
#Service mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  type: ClusterIP
